import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '@/styles/index.scss';

const suitFont = localFont({
  src: './fonts/SUIT-Regular.woff2',
  variable: '--font-SUIT',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${suitFont.variable}`}>{children}</body>
    </html>
  );
}
